image: debian/stable
packages:
  - lua5.3
  - lua5.3-dev
  - xxd
  - build-essential
sources:
  - https://git.sr.ht/~shakna/doublegoodplus
tasks:
  - test: |
     cd doublegoodplus
     lua5.3 -v
     make -j $(nproc --all) test
